LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE       := AuroraServices
LOCAL_MODULE_OWNER := auroraoss
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES    := prebuilt/AuroraServices.apk
LOCAL_MODULE_SUFFIX      := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE        := PRESIGNED
LOCAL_PRIVILEGED_MODULE  := true
LOCAL_DEX_PREOPT         := false

include $(BUILD_PREBUILT)
